doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                override_url: true
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '5.7'
            debtors_register:
                url: '%env(resolve:DEBTORS_REGISTER_DATABASE_URL)%'
                server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
